CREATE TABLE Quadrados (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lado      NUMBER,
    perimetro NUMBER,
    área      NUMBER
);

SELECT * FROM quadrados

CREATE OR REPLACE PROCEDURE insereQuadrado (
    p_lado IN NUMBER
) AS 
    v_perimetro NUMBER;
    v_area NUMBER;
BEGIN
    -- Realizando os cálculos matemáticos
    -- Perímetro: 4 * lado
    -- Área: lado * lado
    v_perimetro := 4 * p_lado;
    v_area := p_lado * p_lado;

    -- Inserindo os dados na tabela
    -- Nota: O campo 'id' assume-se que seja gerado por uma Identity Column ou Sequence
    INSERT INTO Quadrados (lado, perimetro, área)
    VALUES (p_lado, v_perimetro, v_area);

    -- Confirma a transação
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Quadrado inserido com sucesso! Lado: ' || p_lado);
END insereQuadrado;

EXEC insereQuadrado(20);